---
root: true

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

plugins:
  - react

extends:
 - eslint:recommended
 - plugin:react/recommended

env:
  browser: true

rules:
  no-console: off
  # How to change code so I can remove these warnings below (they are errors by default)?
  no-undef: warn
  no-unused-vars: warn
  react/jsx-no-undef: warn
  react/prop-types: warn
  react/react-in-jsx-scope: warn