---
root: true

parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    jsx: true

plugins:
  - react

extends:
 - eslint:recommended
 - plugin:react/recommended

env:
  browser: true

rules:
  no-console: off
