---
root: false

parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

plugins:
  - react

extends:
 - eslint:recommended
 - plugin:react/recommended

env:
  jest: true
  node: false